apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-etsmtl
  namespace: cert-manager
spec:
  acme:
    email: cedille@etsmtl.ca
    privateKeySecretRef:
      name: letsencrypt-http
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token-etsmtl
            key: token
      selector:
        dnsZones:
        - etsmtl.club
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-etsmtl-stg
  namespace: cert-manager
spec:
  acme:
    email: cedille@etsmtl.ca
    privateKeySecretRef:
      name: letsencrypt-http-stg
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token-etsmtl
            key: token
      selector:
        dnsZones:
        - etsmtl.club
