apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-external-dns"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      destination:
        namespace: external-dns
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - repoURL: registry-1.docker.io/bitnamicharts
          chart: external-dns
          targetRevision: 9.0.3
          # releaseName: external-dns
          helm:
              valueFiles:
                - $values/common/external-dns/values.yaml
        - repoURL: 'https://github.com/ClubCedille/k8s-base.git'
          targetRevision: master
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
