apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contour
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-contour"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: project-contour
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - chart: contour
          helm:
            parameters:
              - name: envoy.service.type
                value: "LoadBalancer"
          repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 19.3.1
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
