apiVersion: redhatcop.redhat.io/v1alpha1
kind: Group
metadata:
  name: authentik-admin
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: authentik-admin
  type: external
  policies:
    - authentik-admin
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupAlias
metadata:
  name: authentik-admin
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: authentik Admins
  groupName: authentik-admin
  authEngineMountPath: oidc/authentik/
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Group
metadata:
  name: exec-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: exec-cedille
  type: external
  policies:
    - exec-cedille
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupAlias
metadata:
  name: exec-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: exec-cedille
  groupName: exec-cedille
  authEngineMountPath: oidc/authentik/
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Group
metadata:
  name: club-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: club-cedille
  type: external
  policies:
    - club-cedille
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupAlias
metadata:
  name: club-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: club-cedille
  groupName: club-cedille
  authEngineMountPath: oidc/authentik/
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Group
metadata:
  name: exec-applets
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: exec-applets
  type: external
  policies:
    - exec-applets
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupAlias
metadata:
  name: exec-applets
spec:
  authentication:
    path: kubernetes
    role: config-admin
  name: exec-applets
  groupName: exec-applets
  authEngineMountPath: oidc/authentik/
---
