apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: authentik-admin
spec:
  authentication:
    path: kubernetes
    role: config-admin
  policy: |
    path "*" {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    path "sys/auth/*" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }

    path "sys/mounts/*" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }

    path "sys/policies/acl/*" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }

    path "auth/token/*" {
      capabilities = ["create", "read", "update", "delete", "sudo"]
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: exec-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  policy: |
    path "kv/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "kv-system/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "kv-v2/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "kv-v2/metadata" {
      capabilities = ["list"]
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: club-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  policy: |
    path "kv/*" {
      capabilities = ["create", "update", "list"]
    }

    path "kv-system/*" {
      capabilities = ["create", "list"]
    }

    path "kv-v2/*" {
      capabilities = ["create", "update", "list"]
    }

    path "kv-v2/metadata" {
      capabilities = ["list"]
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: exec-applets
spec:
  authentication:
    path: kubernetes
    role: config-admin
  policy: |
    path "kv/data/applets/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "kv/data/planifets-*/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "kv/metadata/planifets-*/*" {
      capabilities = ["read", "list"]
    }
