apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - resources/backupstoragelocation.yaml

helmCharts:
  - name: velero
    version: "9.0.4"
    repo: https://vmware-tanzu.github.io/helm-charts
    releaseName: "velero"
    namespace: velero
    valuesFile: "helm/values.yaml"
