apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-velero"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-1000"
    spec:
      destination:
        namespace: velero
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - chart: velero
          helm:
            parameters:
              - name: configuration.features
                value: EnableCSI

              - name: deployNodeAgent
                value: "true"
              - name: nodeAgent.tolerations[0].operator
                value: Exists
              - name: nameOverride
                value: velero
              - name: fullnameOverride
                value: velero

              - name: configuration.backupStorageLocation[0].bucket
                value: "{{ .name }}-bucket"
              - name: configuration.backupStorageLocation[0].name
                value: default
              - name: configuration.backupStorageLocation[0].prefix
                value: velero
              - name: configuration.backupStorageLocation[0].provider
                value: aws
              - name: configuration.backupStorageLocation[0].accessMode
                value: ReadWrite
              - name: configuration.backupStorageLocation[0].default
                value: "true"
              - name: configuration.backupStorageLocation[0].config.region
                value: ca-east-006
              - name: configuration.backupStorageLocation[0].config.s3Url
                value: https://s3.ca-east-006.backblazeb2.com

              - name: credentials.useSecret
                value: "true"
              - name: credentials.existingSecret
                value: velero-b2-credentials

              - name: initContainers[0].name
                value: velero-plugin-for-aws
              - name: initContainers[0].image
                value: velero/velero-plugin-for-aws:v1.13.1
              - name: initContainers[0].volumeMounts[0].mountPath
                value: /target
              - name: initContainers[0].volumeMounts[0].name
                value: plugins
              - name: configuration.backupStorageLocation[0].config.checksumAlgorithm
                value: "" # Required for Backblaze B2 — https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/247

              - name: image.imagePullSecrets[0]
                value: dockerhub-pull
              - name: kubectl.image.repository
                value: public.ecr.aws/bitnami/kubectl
              - name: kubectl.image.tag
                value: "1.30"

          repoURL: https://vmware-tanzu.github.io/helm-charts/
          targetRevision: 9.0.4
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/warn: privileged
            pod-security.kubernetes.io/audit: privileged
        syncOptions:
          - CreateNamespace=true

