apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-velero"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-1000"
    spec:
      destination:
        namespace: velero
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - chart: vmware-tanzu/velero
          helm:
            parameters:
              - name: configuration.backupStorageLocation[0].bucket
                value: "{{ .name }}-bucket"
              - name: configuration.backupStorageLocation[0].name
                value: b2
              - name: configuration.backupStorageLocation[0].provider
                value: aws
              - name: configuration.backupStorageLocation[0].accessMode
                value: ReadWrite
              - name: configuration.backupStorageLocation[0].config.region
                value: ca-east-006
              - name: configuration.backupStorageLocation[0].config.s3Url
                value: https://s3.ca-east-006.backblazeb2.com
              - name: credentials.useSecret
                value: "true"
              - name: credentials.existingSecret
                value: velero-b2-credentials
              - name: initContainers[0].name
                value: velero-plugin-for-aws
              - name: initContainers[0].image
                value: velero/velero-plugin-for-aws:v1.8.2
              - name: initContainers[0].volumeMounts[0].mountPath
                value: /target
              - name: initContainers[0].volumeMounts[0].name
                value: plugins
          repoURL: https://vmware-tanzu.github.io/helm-charts/
          targetRevision: 8.6.0
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
