apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: netdata
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-netdata"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: netdata
        server: "{{.server}}"
      project: "{{.name}}"
      source:
        repoURL: https://github.com/ClubCedille/k8s-base.git
        targetRevision: HEAD
        path: common/netdata
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
