apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-ips
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            etsmtl.club/external-network: "true"
  template:
    metadata:
      name: '{{.name}}-external-ip'
      annotations:
        argocd.argoproj.io/sync-wave: "-80"
    spec:
      project: "{{.name}}"
      ignoreDifferences:
      - group: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      source:
        repoURL: https://github.com/ClubCedille/k8s-base/
        targetRevision: HEAD
        path: common/external-ip
        kustomize:
          patches:
            - patch: |-
                - op: add
                  path: /spec/addresses/0
                  value: '{{  index .metadata.annotations "etsmtl.club/external-ip" }}/32'
              target:
                kind: IPAddressPool
      destination:
        server: '{{.server}}'
        namespace: metallb-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
