apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  addresses: []
  namespaces:
  - contour-external
  - contour
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - public-ip
  nodeSelectors:
  - matchLabels:
      etsmtl.club/external-network: "true"
