apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  addresses:
    - 142.137.247.74/32
    - 142.137.247.76/32
    - 142.137.247.78/32
  serviceAllocation:
    namespaces:
      - contour-external
      - contour
      - forgejo
      - byzantium-helm
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-ip
  nodeSelectors:
    - matchLabels:
        etsmtl.club/external-network: "true"
