apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: routes
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: routes
  template:
    metadata:
      labels:
        app: routes
    spec:
      hostNetwork: true
      containers:
      - name: routes
        image: alpine
        command:
        - /bin/sh
        - -c
        args:
        - |
          export VLAN_DEVICE=$(ip route | grep 142.137.247.0/24 | grep -o 'enx[a-zA-Z0-9]*' | head -n 1)
          ip route add 142.137.247.0/24 dev $VLAN_DEVICE table 100
          ip route add default via 142.137.247.1 table 100
          ip rule add from 142.137.247.0/24 lookup 100
          ip rule add to 142.137.247.0/24 lookup 100
          exec sleep infinity
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: Exists
      nodeSelector:
        etsmtl.club/external-network: "true"
