apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: github
spec:
  authentication:
    path: kubernetes
    role: config-admin
  type: github
  path: github
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineConfig
metadata:
  name: gh-engine-cedille
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: github
  applicationID: 639042
  sSHKeyReference:
    vaultSecret:
      path: kv-system/github/clubcedille
