apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-255"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    sources:
      - repoURL: 'https://github.com/ceph/ceph-csi-operator.git'
        targetRevision: v0.2.0
        path: deploy/all-in-one
    # directory:
    #   recurse: true
    #   include: "{*.argoapp.yaml,*.argoapp.yml}"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
