apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph-external
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ClubCedille/k8s-base
    path: bases/common/rook/ressources
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
