apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "gitops-{{.name}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: "{{.name}}"
      destination:
        server: "{{.server}}"
        namespace: argocd
      source:
        repoURL: https://github.com/ClubCedille/{{.name}}
        path: .
        targetRevision: HEAD
        directory:
          recurse: true
          include: "{*.argoapp.yaml,*.argoapp.yml}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true