apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coroot-ce
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-coroot-ce"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: coroot
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - chart: coroot-ce
          helm:
            valueFiles:
              - $values/common/coroot-ce/values.yaml
          repoURL: https://coroot.github.io/helm-charts
          targetRevision: v0.3.1
        - repoURL: 'https://github.com/ClubCedille/k8s-base.git'
          targetRevision: master
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels: 
            pod-security.kubernetes.io/enforce: privileged
