apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contour-internal
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-base
  template:
    metadata:
      name: "{{.name}}-contour-internal"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: contour-internal
        server: "{{.server}}"
      project: "{{.name}}"
      source:
        repoURL: registry-1.docker.io/bitnamicharts
        chart: contour
        targetRevision: 19.5.11
        helm:
          values: |
            envoy:
              service:
                type: LoadBalancer
              image:
                registry: docker.io
                repository: envoyproxy/envoy
                tag: v1.31.10
            global:
              security:
                allowInsecureImages: true
            contour:
              replicaCount: 2
              ingressClass:
                name: contour-internal
                default: false
              envoyServiceNamespace: contour-internal
              envoyServiceName: contour-internal-envoy
              manageCRDs: false
              leaderElection:
                leaseDuration: 60s
                renewDeadline: 50s
                retryPeriod: 10s
              image:
                registry: ghcr.io
                repository: projectcontour/contour
                tag: v1.30.5
            namespaceOverride: contour-internal
          releaseName: contour-internal
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
