apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contour-internal

helmCharts:
  - name: contour
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 19.5.11
    releaseName: contour-internal
    valuesInline:
      envoy:
        service:
          type: LoadBalancer
      contour:
        ingressClass:
          name: contour-internal
          default: false
        envoyServiceNamespace: contour-internal
        envoyServiceName: contour-internal-envoy
        manageCRDs: false
        image:
          registry: "public.ecr.aws"
          repository: "bitnami/contour"
          tag: "1.30.3-debian-12-r4"
      namespaceOverride: contour-internal
