apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contour-internal

helmCharts:
  - name: contour
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 19.5.11
    releaseName: contour-internal
    valuesInline:
      envoy:
        service:
          type: LoadBalancer
      contour:
        ingressClass:
          name: contour-internal
          default: false
        envoyServiceNamespace: contour-internal
        envoyServiceName: contour-internal-envoy
        manageCRDs: false
      namespaceOverride: contour-internal
