apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contour-internal

helmCharts:
  - name: contour
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 19.5.10
    releaseName: contour-internal
    valuesInline:
      envoy:
        service:
          type: LoadBalancer
        extraArgs:
          - --base-id 2
      contour:
        ingressClass:
          name: contour-internal
          default: false
      # ingress:
        # ingressClassName: contour-internal
      namespaceOverride: contour-internal
