apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["v1"]
    resources: ["secrets"]
    verbs: ["create", "update", "watch", "list", "patch"]
