apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contour-external
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-contour-internal"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: contour-external
        server: "{{.server}}"
      project: "{{.name}}"
      sources:
        - chart: contour
          helm:
            parameters:
              - name: envoy.service.type
                value: "LoadBalancer"
              - name: ingressClass.name
                value: "contour-external"
              - name: ingressClassName
                value: "contour-external"
              - name:  namespaceOverride
                value: "contour-external"
              - name: fullnameOverride
                value: "contour-external"
          repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 19.5.10
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
