apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contour-external
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-contour-external"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-70"
    spec:
      destination:
        namespace: contour-external
        server: "{{.server}}"
      project: "{{.name}}"
      source:
        repoURL: registry-1.docker.io/bitnamicharts
        chart: contour
        targetRevision: 19.5.11
        helm:
          values: |
            global:
              security:
                allowInsecureImages: true
            envoy:
              service:
                type: LoadBalancer
              image:
                registry: public.ecr.aws
                repository: bitnami/envoy
                tag: 1.31.4-debian-12-r0
            contour:
              envoyServiceNamespace: contour-external
              envoyServiceName: contour-external-envoy
              image:
                registry: public.ecr.aws
                repository: bitnami/contour
                tag: 1.30.3-debian-12-r4
            namespaceOverride: contour-external
          releaseName: contour-internal
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
