apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contour-external

helmCharts:
  - name: contour
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 19.5.10
    releaseName: contour-external
    valuesInline:
      envoy:
        service:
          type: LoadBalancer
        extraArgs:
          - --base-id 1
      contour:
        envoyServiceNamespace: contour-external
        envoyServiceName: contour-external-envoy
      namespaceOverride: contour-external