apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-ip
  namespace: metallb-system
spec:
  addresses: []
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal-ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - internal-ip
  nodeSelectors:
  - matchLabels:
      etsmtl.club/internal-network: "true"
