apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-254"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ClubCedille/k8s-base
    path: common/ceph-csi/drivers/ressources
    targetRevision: HEAD
    # directory:
    #   recurse: true
    #   include: "{*.argoapp.yaml,*.argoapp.yml}"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
