apiVersion: v1
kind: Service
metadata:
  name: contour-loadbalancer
  namespace: ingress-contour
  labels:
    app: contour
spec:
  type: LoadBalancer
  loadBalancerIP: 142.137.247.78
  selector:
    app: contour
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
