apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  destination:
    namespace: project-contour
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: contour
      helm:
        parameters:
          - name: envoy.service.type
            value: "LoadBalancer"
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 1.30.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
