apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: authentik
spec:
  authentication:
    path: kubernetes
    role: config-admin
  type: oidc
  path: oidc
  description: Authentik OIDC authentication
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: authentik-oidc-config
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: oidc/authentik
  OIDCDiscoveryURL: https://auth.etsmtl.club/application/o/vault/
  OIDCCredentials:
    secret:
      name: authentik-oidc-secret
    usernameKey: clientID
    passwordKey: clientSecret
  defaultRole: exec
  JWTSupportedAlgs:
    - HS256
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineRole
metadata:
  name: authentik-exec
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: oidc/authentik
  name: exec
  userClaim: email
  groupsClaim: groups
  allowedRedirectURIs:
    - https://vault.etsmtl.club/ui/vault/auth/oidc/authentik/oidc/callback
    - https://vault.etsmtl.club/oidc/callback
    - http://localhost:8250/oidc/callback
  OIDCScopes:
    - openid
    - profile
    - email
    - groups
  tokenPolicies:
    - reader
  tokenTTL: 24h
  tokenMaxTTL: 24h
---
